version: '3'

services:

  minical:
    image: custom-php
    container_name: minical
    ports:
      - "80:80"
    volumes:
      - ./.env:/var/www/html/.env
      - ./public:/var/www/html/public
    depends_on:
      - db

  db:
    image: mysql:5.6
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./db_data:/var/lib/mysql
